name: mpv_native_texture_demo
description: Demo app for mpv_native_texture (libmpv-backed Flutter Windows texture).
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.2
  mpv_native_texture:
    path: packages/mpv_native_texture

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
